name: CI on Branched and PRs

on:
  push:
    branches: ['Feature/Migrate**']
    paths:
      - "src/**"
  pull_request:
    branches: [ master ]
    paths:
      - "src/**"

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow


